# Where things are
source:             .
build:              static
destination:        .whdist/.build

# Relative to source
scripts_dir:        scripts
styles_dir:         styles
sprites_dir:        sprites
images_dir:         images

# Serving
url:                {SLUSH{=url}}
error:              404.html
single_page:        {SLUSH{ if (spa) { print(true) } else { print(false) } }} # If true, all 404s will be redirect to the index

{SLUSH{ if (github) { }}
# Releaser
github_token:       {SLUSH{=githubToken}}
{SLUSH{ } }}

# Output paths (relative to build location)
styles_path:        css
scripts_path:       javascript
images_path:        images
sprites_path:       sprites

{SLUSH{ if (deployer === 'aws') { }}
# Deployer
deployer:
  type:             aws
  bucket:           {SLUSH{ if (awsBucket) { print(awsBucket) } }}
{SLUSH{ } }}

# Build tools
styles:
  autoprefixer:     last 2 versions
{SLUSH{ if (framework === 'bootstrap') { }}
  sass:
    importMappings:
      -
        search:     ^bootstrap/(.+)
        replace:    node_modules/bootstrap/scss/$1
{SLUSH{ } else if (framework === 'starter-kit') { }}
  sass:
    importMappings:
      -
        search:     ^breakpoint$
        replace:    node_modules/breakpoint-sass/stylesheets/_breakpoint.scss
      -
        search:     ^bourbon$
        replace:    node_modules/bourbon/app/assets/stylesheets/_bourbon.scss
  postcss:
    plugins:
      - name:       lost
{SLUSH{ } }}
